[dependencies]
itertools = "0.8"
proc-macro2 = "1"
quote = "1"
synstructure = "0.12.1"

[dependencies.syn]
features = ["full"]
version = "1"

[lib]
proc-macro = true

[package]
authors = ["The Rust Project Developers"]
edition = "2018"
name = "rustfmt_macros"
version = "0.1.0"
