[dependencies]
indexmap = "1"

[dependencies.smallvec]
features = ["union", "may_dangle"]
version = "1.0"

[lib]
name = "serialize"
path = "lib.rs"

[package]
authors = ["The Rust Project Developers"]
edition = "2018"
name = "rustfmt_serialize"
version = "0.0.0"
